/*
 * This source file was generated by the Gradle 'init' task
 */
package es.burgueses;

import es.burgueses.presentacion.controladores.MainApp;
import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        Application.launch(MainApp.class, args);
    }

    public void someMethod() {
        getClass().getResource("/paginaPrincipal.fxml");
    }
}