/*
 * This source file was generated by the Gradle 'init' task
 */
package es.burgueses;

import es.burgueses.presentacion.controladores.Main;
import javafx.application.Application;

public class App {

    public static void main(String[] args) {
         Application.launch(Main.class, args);


    }
}