/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ies.sequeros.dam;

import ies.sequeros.dam.aplicacion.mecanicos.NuevoMecanicoCasoUso;
import ies.sequeros.dam.dominio.IMecanicoRepositorio;
import ies.sequeros.dam.dominio.Mecanico;
import ies.sequeros.dam.infraestructura.MecanicoRepositorioEnFichero;
import ies.sequeros.dam.presentacion.main.Main;
import javafx.application.Application;

public class App {

    public static void main(String[] args) {
         Application.launch(Main.class, args);


    }
}
