/*
 * This source file was generated by the Gradle 'init' task
 */
package es.burgueses.dominio;

import org.junit.Test;

import es.burgueses.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
