/*
 * This source file was generated by the Gradle 'init' task
 */
package es.burgueses.dominio;



import es.burgueses.App;
import es.burgueses.dominio.infraestructura.IUsuarioMongoTest;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        IUsuarioMongoTest usuarioMongoTest = new IUsuarioMongoTest();
    }
}
